### ISSUE TITLE
Hangman - Kleinigkeiten

### ISSUE THREAD

**Issue by ThomasWeis** [SophieBartmann/InfinitumBot#2]
- "Noch keine falschen Buchstaben" anzeigen, wenn .hint benutzt wird und noch keine Fehlversuche gemacht wurden
- Leerzeichen zwischen falsch geratenen Buchstaben
- Leerzeichen zwischen "Das richtige Wort wäre gewesen:" und Lösung
- Bei .spielregeln im Query fehlt der letzte Teil nach "Zulässig sind alle Wörter, die deutsch oder im deutschen Sprachraum geläufig sind, " und "Punktestand kann mit .score abgefragt werden" könnte am Schluss noch dazu

**Comment by SophieBartmann** [comment]
Done(But on the other bot)
